---
- name: Build Server Config
  hosts: amazon
  become: yes
   
  tasks:
    - name: Installing java
      yum:
        name: java-1.8.0*
        state: present

    - name: Install maven
      package: 
        name: maven
        state: present
...   
